# Generated by Django 2.2.5 on 2019-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.UUIDField(),
        ),
    ]
