# Generated by Django 2.2.5 on 2019-09-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shippingRegion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippingRegion.ShippingRegion')),
            ],
        ),
    ]
