# Generated by Django 2.2.5 on 2019-09-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=150, null=True)),
                ('image_2', models.CharField(max_length=150, null=True)),
                ('thumbnail', models.CharField(max_length=150, null=True)),
                ('display', models.SmallIntegerField()),
            ],
        ),
    ]
