# Generated by Django 2.2.5 on 2019-09-16 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('shipped_on', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('auth_code', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipping')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.Tax')),
            ],
        ),
    ]
