# Generated by Django 2.2.5 on 2019-09-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='uni_cost',
            new_name='unit_cost',
        ),
    ]
